import AstrolabeCategory.Signature
import Mathlib.CategoryTheory.PathCategory.Basic

/-!
# The Astrolabe Category A(Σ) := Free(Σ)

Given an astrolabe signature Σ = (O, M, h), we construct the free category
generated by Σ. This is the path category on the quiver induced by Σ.
-/

universe u

namespace AstrolabeCategory

open CategoryTheory

/-- A signature induces a quiver: objects are O, arrows are M. -/
instance signatureQuiver (sig : Signature.{u}) : Quiver sig.O where
  Hom a b := { m : sig.M // sig.s m = a ∧ sig.t m = b }

/-- The astrolabe category A(sig) is the free category (path category) on the
    quiver induced by sig. Objects are O, morphisms are composable paths. -/
def AstrolabeCat (sig : Signature.{u}) := Paths sig.O

/-- A(sig) is a category (inherited from Paths). -/
instance astrolabeCatCategory (sig : Signature.{u}) :
    Category (AstrolabeCat sig) :=
  Paths.categoryPaths sig.O

/-- The inclusion of generators into A(sig), as a prefunctor. -/
def generators (sig : Signature.{u}) : sig.O ⥤q AstrolabeCat sig :=
  Paths.of sig.O

-- ============================================================
-- Proposition 3.2: Well-definedness (four category axioms)
-- ============================================================

/-- **Proposition 3.2 (i)**: Left identity — `id ≫ f = f`. -/
theorem well_def_id_comp (sig : Signature.{u})
    {a b : AstrolabeCat sig} (f : a ⟶ b) :
    𝟙 a ≫ f = f :=
  Category.id_comp f

/-- **Proposition 3.2 (ii)**: Right identity — `f ≫ id = f`. -/
theorem well_def_comp_id (sig : Signature.{u})
    {a b : AstrolabeCat sig} (f : a ⟶ b) :
    f ≫ 𝟙 b = f :=
  Category.comp_id f

/-- **Proposition 3.2 (iii)**: Associativity. -/
theorem well_def_assoc (sig : Signature.{u})
    {a b c d : AstrolabeCat sig}
    (f : a ⟶ b) (g : b ⟶ c) (h : c ⟶ d) :
    (f ≫ g) ≫ h = f ≫ (g ≫ h) :=
  Category.assoc f g h

-- ============================================================
-- Proposition 3.3: Representability (universal property)
-- ============================================================

/-- **Proposition 3.3 (existence)**: Any prefunctor from the quiver
    lifts to a functor from A(sig). -/
def representability_lift {sig : Signature.{u}}
    {C : Type*} [Category C] (φ : sig.O ⥤q C) :
    AstrolabeCat sig ⥤ C :=
  Paths.lift φ

/-- **Proposition 3.3 (specification)**: The lifted functor agrees
    with φ on generators. -/
theorem representability_spec {sig : Signature.{u}}
    {C : Type*} [Category C] (φ : sig.O ⥤q C) :
    Paths.of sig.O ⋙q (representability_lift φ).toPrefunctor = φ :=
  Paths.lift_spec φ

/-- **Proposition 3.3 (uniqueness)**: The lifted functor is unique. -/
theorem representability_unique {sig : Signature.{u}}
    {C : Type*} [Category C] (φ : sig.O ⥤q C)
    (F : AstrolabeCat sig ⥤ C)
    (hF : Paths.of sig.O ⋙q F.toPrefunctor = φ) :
    F = representability_lift φ :=
  Paths.lift_unique φ F hF

-- ============================================================
-- Identity and composition of functors
-- ============================================================

/-- The identity functor on A(sig) exists. -/
def identityFunctor (sig : Signature.{u}) :
    AstrolabeCat sig ⥤ AstrolabeCat sig :=
  𝟭 (AstrolabeCat sig)

/-- Functors out of A(sig) compose. -/
def functorComposition {sig : Signature.{u}}
    {C D : Type*} [Category C] [Category D]
    (F : AstrolabeCat sig ⥤ C) (G : C ⥤ D) :
    AstrolabeCat sig ⥤ D :=
  F ⋙ G

/-- Composition with identity is identity (left). -/
theorem comp_id_functor {sig : Signature.{u}}
    {C : Type*} [Category C] (F : AstrolabeCat sig ⥤ C) :
    identityFunctor sig ⋙ F = F :=
  Functor.id_comp F

/-- Functor composition is associative. -/
theorem functor_assoc {sig : Signature.{u}}
    {C D E : Type*} [Category C] [Category D] [Category E]
    (F : AstrolabeCat sig ⥤ C) (G : C ⥤ D) (H : D ⥤ E) :
    (F ⋙ G) ⋙ H = F ⋙ (G ⋙ H) :=
  Functor.assoc F G H

end AstrolabeCategory
