import AstrolabeCategory.Signature
import Mathlib.CategoryTheory.PathCategory.Basic

/-!
# The Astrolabe Category A(Σ) := Free(Σ)

Given an astrolabe signature Σ = (O, M, h), we construct the free category
generated by Σ. This is the path category on the quiver induced by Σ.

The construction uses Mathlib's `CategoryTheory.Paths`, which gives the
free category on a quiver (objects = vertices, morphisms = composable paths).
-/

universe u

namespace AstrolabeCategory

open CategoryTheory

/-- A signature induces a quiver: objects are O, arrows are M. -/
instance signatureQuiver (sig : Signature.{u}) : Quiver sig.O where
  Hom a b := { m : sig.M // sig.s m = a ∧ sig.t m = b }

/-- The astrolabe category A(sig) is the free category (path category) on the
    quiver induced by sig. Objects are O, morphisms are composable paths of M. -/
def AstrolabeCat (sig : Signature.{u}) := Paths sig.O

/-- A(sig) is a category (inherited from Paths). -/
instance (sig : Signature.{u}) : Category (AstrolabeCat sig) :=
  Paths.categoryPaths sig.O

/-- The inclusion of generators into A(sig), as a prefunctor. -/
def generators (sig : Signature.{u}) : sig.O ⥤q AstrolabeCat sig :=
  Paths.of sig.O

end AstrolabeCategory
