# -*- mode: python ; coding: utf-8 -*-
# PyInstaller spec for astrolabe backend sidecar

a = Analysis(
    ['astrolabe_app/server.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'astrolabe_app',
        'astrolabe_app.astrolabe_router',
        'astrolabe_app.storage',
        'astrolabe_app.routes.docs',
        'astrolabe_app.routes.files',
        'astrolabe_app.routes.project',
        'astrolabe_app.routes.viewport',
        'astrolabe_app.analysis',
        'astrolabe_app.analysis.graph_builder',
        'astrolabe_app.analysis.degree',
        'astrolabe_app.analysis.centrality',
        'astrolabe_app.analysis.dag',
        'astrolabe_app.analysis.community',
        'astrolabe_app.analysis.cluster',
        'astrolabe_app.analysis.skeleton_graph',
        'astrolabe_app.analysis.merge_proofs',
        'astrolabe_app.analysis.router',
        'uvicorn',
        'uvicorn.logging',
        'uvicorn.loops',
        'uvicorn.loops.auto',
        'uvicorn.protocols',
        'uvicorn.protocols.http',
        'uvicorn.protocols.http.auto',
        'uvicorn.protocols.websockets',
        'uvicorn.protocols.websockets.auto',
        'uvicorn.lifespan',
        'uvicorn.lifespan.on',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='astrolabe-server',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
